//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitWin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;meta content=&quot;ie=edge&quot; http-equiv=&quot;x-ua-compatible&quot; /&gt;&lt;style&gt;html,body,.c-root{height:100%}body{-ms-user-select:none;/* BorderC */background-color:#204060;/* ForeC */color:#000;cursor:default;font-family:Meiryo;margin:0;overflow:hidden;user-select:none}.c-node{display:flex;flex:1 0;}.c-node:nth-child(n+2){margin-left:2px}.column{flex-direction:column;}.column &gt; .c-node:nth-child(n+2){margin:2px 0 0 0}.column &gt; .side{margin:0 2px}menu,article{/* BackC */background-colo [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;&lt;meta charset=&quot;utf-8&quot; /&gt;&lt;meta content=&quot;ie=edge&quot; http-equiv=&quot;x-ua-compatible&quot; /&gt;&lt;style&gt;html{height:100%}body{-ms-user-select:none;background-color:#f2f2f2;cursor:default;height:100%;margin:0;user-select:none}form{display:flex;flex-direction:column;height:100%}section{flex:1 0;overflow-y:scroll;position:relative}footer{border-top:solid 1px #bfbfbf;flex:0 60px;padding-right:12px;text-align:right}h2{font:normal 20px/1 Meiryo;margin:64px 0 8px 32px;}h2:first-child{margin-top:32px}h3{font:normal 16 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;number&quot;:[{&quot;x&quot;:&quot;0.5&quot;,&quot;y&quot;:&quot;0.5&quot;,&quot;width&quot;:&quot;800&quot;,&quot;height&quot;:&quot;600&quot;,&quot;name&quot;:&quot;800px 600px&quot;},{&quot;x&quot;:&quot;0.5&quot;,&quot;y&quot;:&quot;0.5&quot;,&quot;width&quot;:&quot;0.6&quot;,&quot;height&quot;:&quot;0.6&quot;,&quot;name&quot;:&quot;60% 60%&quot;},{&quot;x&quot;:&quot;0.5&quot;,&quot;y&quot;:&quot;0.5&quot;,&quot;width&quot;:&quot;0.8&quot;,&quot;height&quot;:&quot;0.8&quot;,&quot;name&quot;:&quot;80% 80%&quot;},{&quot;x&quot;:&quot;0.5&quot;,&quot;y&quot;:&quot;0.5&quot;,&quot;width&quot;:&quot;0.6&quot;,&quot;height&quot;:&quot;1.0&quot;,&quot;name&quot;:&quot;60% 100%&quot;}],&quot;template&quot;:[{},{&quot;c&quot;:[{&quot;g&quot;:60},{&quot;g&quot;:60}],&quot;d&quot;:false},{&quot;c&quot;:[{&quot;c&quot;:[{&quot;g&quot;:60},{&quot;g&quot;:60}],&quot;d&quot;:false,&quot;g&quot;:60},{&quot;c&quot;:[{&quot;g&quot;:60},{&quot;g&quot;:60}],&quot;d&quot;:false,&quot;g&quot;:60}],&quot;d&quot;:true... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
